name: uv_net
channels:
  - pytorch
  - lambouj
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - occwl
  - pytorch
  - pytorch-lightning
  - torchmetrics
  - dgl-cuda11.0=0.6.1=py39_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - torchmetrics=0.3.2
  - tqdm=4.59.0
  - trimesh=3.9.18